apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dice
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    backoffLimit: 25
    activeDeadlineSeconds: 20
    spec:
      template:
        spec:
            containers:
            -  image: kodekloud/throw-dice
               name: throw-dice
            restartPolicy: Never