apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim
  labels:
    name: log-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: manual
  selector:
    matchLabels:
      name: "log-volume"