apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: voting-app
spec:
  selector:
    app: voting-app
    name: result-app-pod
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer