apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: voting-app
spec:
  selector:
    app: voting-app
    name: voting-app-pod
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer